### ISSUE TITLE
Problems with blank? , to_a and collect

### ISSUE THREAD

**Issue by danielvlopes** [mislav/rspec-rails-mocha#1]
I trying to use rspec 1.2.4 with Ruby on Rails 2.3.2 but when I try this:

<pre>
def make_bank_account(attributes = {})
  account = mock_model(Account)
end
</pre>

These methods failed: blank? , is_a? , collect

**Comment by mislav** [comment]
Can you please be more specific? What does it mean that "the methods failed"?

**Comment by danielvlopes** [comment]
I think AR objects look for these methods, take a look on what I do to get this error:

spec_helper.rb :

<pre>
ENV["RAILS_ENV"] = "test"
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'spec'
require 'spec/rails'
require 'rspec_rails_mocha'
require File.expand_path(File.dirname(__FILE__) + "/blueprints")

Spec::Runner.configure do |config|
...
</pre>


bank_account_spec.rb (the spec where I use mock_model)

<pre>
require File.dirname(__FILE__) + '/../spec_helper'

describe BankAccount do

  def make_bank_account(attributes = {})
    account = mock_model(Account)
    @bank_account = BankAccount.make(:account => account)
  end
  ....
</pre>


As you can see, I'm using mock_model to mock an association in my bank_account model spec. And when I run it these errors appear:

<pre>
undefined method `blank?' for "#<Mocha::Mock:0x35a726c>":Account
</pre>

If I stub blank? I get is_a? and collect undefined.

In this line @bank_account = BankAccount.make(:account => account) , I'm calling the machinist method and send account mock that should behave like a AR object and pass the ID to BankAccount association but get the above errors.

**Comment by mislav** [comment]
Sorry, I never looked into this. Since the project works for other people, I'm going to close this until there's a patch for a specific issue. I don't plan on advancing this project further.
