### ISSUE TITLE
How do I use it!?

### ISSUE THREAD

**Issue by kristianmandrup** [mislav/rspec-rails-mocha#2]
Gemfile

```
group :test, :development do
  # gem "autotest"
  gem "capybara"   
  gem "rspec", '2.0.1'
  gem "rspec-rails", '2.0.1'
  gem 'rspec-rails-mocha'  
end
```

Spec

```
describe "User permissions to operate on Articles" do  
  before do 
    puts "User is defined" if defined? User
    puts "Article is defined" if defined? Article

    editor_user = mock_model(User)
    editor_user.stub!(:name).and_return("Editor user")
    editor_user.stub!(:role).and_return("editor")
...
```

Outcome

```
Failures:
  1) User permissions to operate on Articles should be able to :read Article he owns
     Failure/Error: editor_user = mock_model(User)
     unexpected invocation: #<Mock:User_1001>.__mock_proxy()
     unsatisfied expectations:
     - expected exactly once, not yet invoked: #<Mock:User_1001>.id(any_parameters)
     - expected exactly once, not yet invoked: #<Mock:User_1001>.persisted?(any_parameters)
     - expected exactly once, not yet invoked: #<Mock:User_1001>.destroyed?(any_parameters)
     - expected exactly once, not yet invoked: #<Mock:User_1001>.marked_for_destruction?(any_parameters)
```

Should I perhaps just remove the 'rspec-rails' gem?

**Comment by mislav** [comment]
First of all, you shouldn't include "rspec-rails-mocha" in the "development" group. Have it only in the "test" group, like the README indicates.

Second, it seems like your spec suite is configured to mock with RSpec, not Mocha. Search for `config.mock_with` in your spec setup. When you load "rspec-rails-mocha", it configures RSpec to mock with `:mocha` — this is the way it should be.

**Comment by ksarna** [comment]
Hi Mislav,

First of all, thanks for doing this gem!
Unfortunately, I have same thing as Kristian.

My Gemfile:

```
group :test, :development do
  gem 'rspec-rails'
end

group :test do
  gem 'rspec-rails-mocha'
end
```

---

I also have

config.mock_with :mocha

in spec_helper.rb but still I got

```
 Failure/Error: @user = mock_model(User)
 unexpected invocation: #<Mock:User_1001>.__mock_proxy()
 unsatisfied expectations:
 - expected exactly once, not yet invoked: #<Mock:User_1001>.id(any_parameters)
 - expected exactly once, not yet invoked: #<Mock:User_1001>.persisted?(any_parameters)
 - expected exactly once, not yet invoked: #<Mock:User_1001>.destroyed?(any_parameters)
 - expected exactly once, not yet invoked: #<Mock:User_1001>.marked_for_destruction?(any_parameters)
 # ./spec/controllers/users_controller_spec.rb:52:in `block (3 levels) in <top (required)>'
```

I tried and put 

```
RSpec.configure do |config| 
    config.mock_with :mocha
end
```

inside of the test class to be sure it's set to it but still, the same error.

my versions are as follows:

```
rspec (2.1.0)
  rspec-core (~> 2.1.0)
  rspec-expectations (~> 2.1.0)
  rspec-mocks (~> 2.1.0)
rspec-core (2.1.0)
rspec-expectations (2.1.0)
  diff-lcs (~> 1.1.2)
rspec-mocks (2.1.0)
rspec-rails (2.1.0)
  rspec (~> 2.1.0)
rspec-rails-mocha (0.2.1)
  mocha (>= 0.9.8)
  rspec-rails (>= 2.0.0)
```

**Comment by martinhawkins** [comment]
Hi Mislav,
Great idea but unless I'm missing something, it's not working on my environment.
Ruby - v ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.5.0]
RSpec.configure do |config|
   config.mock_with :mocha
end
    rspec (2.2.0)
      rspec-core (~> 2.2)
      rspec-expectations (~> 2.2)
      rspec-mocks (~> 2.2)
    rspec-core (2.2.1)
    rspec-expectations (2.2.0)
      diff-lcs (~> 1.1.2)
    rspec-mocks (2.2.0)
    rspec-rails (2.2.0)
      rails (~> 3.0.0)
      rspec (~> 2.2)
    rspec-rails-mocha (0.2.1)
      mocha (>= 0.9.8)
      rspec-rails (>= 2.0.0)
Errors similar to ksarna:
@mock_club = mock_model(Club)
produces
unexpected invocation: #Mock:Club_1001.__mock_proxy()
unsatisfied expectations:
- expected exactly once, not yet invoked: #Mock:Club_1001.id(any_parameters)
- expected exactly once, not yet invoked: #Mock:Club_1001.persisted?(any_parameters)
- expected exactly once, not yet invoked: #Mock:Club_1001.destroyed?(any_parameters)
- expected exactly once, not yet invoked: #Mock:Club_1001.marked_for_destruction?(any_parameters)

**Comment by voldy** [comment]
Hi Mislav,
I have the same error as ksarna and martinhawkins with Rails 3 and RSpec 2.1.0.
I looked at `mock_model` and `stub_model` methods in RSpec 2.x and found that these methods were refactored very much since RSpec 1.3.x. 
As I understand rspec-rails-mocha doesn't compatible with RSpec 2.x. or Rails 3.
Can you help us with rspec-rails-mocha 2.0 ? :)

**Comment by tessro** [comment]
This should be fixed in rspec-rails-mocha 0.3.0.  Can you update the gem and check to see that it is resolved?

**Comment by lucassus** [comment]
I have exactly the same problem.

my gems are:

<pre>
ruby-1.9.2-p0$ bundle list | grep mocha
  * mocha (0.9.12)
  * rspec-rails-mocha (0.3.0)
</pre>


<pre>
ruby-1.9.2-p0$ bundle list | grep rspec
  * rspec (2.5.0)
  * rspec-core (2.5.1)
  * rspec-expectations (2.5.0)
  * rspec-instafail (0.1.7)
  * rspec-mocks (2.5.0)
  * rspec-rails (2.5.0)
  * rspec-rails-mocha (0.3.0)
</pre>

**Comment by grimen** [comment]
Anyone got a resolution on this?

**Comment by rjharmon** [comment]
I was able to work around it with   config.include Spec::Rails::Mocha inside the configuration section in spec_helper.rb.  It seems that rspec includes the rspec-mocking stuff and we need the Spec::Rails::Mocha to be done after (or, possibly, instead of) the Rspec version.  

It seems like an ordering problem with Bundler, but that's just a guess, really.  I tried spec'ing them in opposite order but it didn't make any difference.

Maybe this helps somebody.

**Comment by djensen47** [comment]
I'm also having this issue and the work-around suggested does not work.

**Comment by mislav** [comment]
It's true that this is probably broken with Rails 3 and RSpec 2. Not using mocha with RSpec anymore, I'm not a likely person to fix this. However I would accept any pull request from someone who cares enough to make it working.

**Comment by mislav** [comment]
Okay guys try this for Rails 3:

```
# Gemfile
group :development, :test do
  gem 'rspec-rails', '~> 2.4'
end

group :test do
  gem 'rspec-rails-mocha', '~> 0.3.1', :require => false
end

# spec/spec_helper.rb
require 'rspec/rails'
require 'rspec/rails/mocha'
```

Ensure that your "spec_helper.rb" file **doesn't contain** `config.mock_with :rspec`.

**Comment by jfelchner** [comment]
Closing this one out as this seems to be the interim solution to this problem until RSpec loads mocks correctly.
