### ISSUE TITLE
0.2.1 doesn't support Rails 2??

### ISSUE THREAD

**Issue by simianarmy** [mislav/rspec-rails-mocha#5]
I have a standalone version of your rspec_rails_mocha.rb file that I use in my Rails 2.x / rspec-rails 1.3.3 code.
I thought I could use 0.2.1...but right there in the gemspec you have:
gem.add_dependency 'rspec-rails', '>= 2.0.0 

and rspec-rails >= 2.0 is only for Rails3 apps.

Confused..

**Comment by mislav** [comment]
I messed up. You are right, that version was (falsely) for Rails 3. Try to install 0.2.2 and close this issue if it works on Rails 2.

**Comment by simianarmy** [comment]
Yes thank you, fixed!
