### ISSUE TITLE
cpk compatibility issue

### ISSUE THREAD

**Issue by toddwf** [mislav/rspec-rails-mocha#6]
Hi, using this gem with rails3 project that also uses composite primary key gem.  I hit a compatibility issue between this and cpk on a to_sym call when the model has a cpk.  Your thoughts? 

I have a patch, I can submit a pull request if you are interested.

see below in mocha.rb line 193:

```
     defined?(model_class.composite?) && model_class.composite? ? primary_key = model_class.primary_key.join.to_sym : primary_key = model_class.primary_key.to_sym
```

**Comment by mislav** [comment]
Thanks for reporting the bug. This is just a dirty workaround, however, and not a full solution. If you would like to patch this, I would expect you to iterate through the `primary_key` array and perform the same operations for each key that we currently do if there's only one primary key.

**Comment by mislav** [comment]
See discussion in #8
