### ISSUE TITLE
Mocha deprecation warnings

### ISSUE THREAD

**Issue by fbjork** [mislav/rspec-rails-mocha#9]
Get the following warnings when I launch rspec with the latest Rails. Any chance you can fix?

```
*** Mocha deprecation warning: Change `require 'mocha'` to `require 'mocha/setup'`.
*** Mocha deprecation warning: Test::Unit or MiniTest must be loaded *before* Mocha.
*** Mocha deprecation warning: If you're integrating with a test library other than Test::Unit or MiniTest, you should use `require 'mocha/api'` instead of `require 'mocha'`.
```

**Comment by mislav** [comment]
I got really frustrated trying to fix similar Mocha deprecation warnings recently (not in this context, though). The way it works and hooks into test frameworks is such a clusterfuck, I think I don't have any motivation to deal with it anymore. A contribution is welcome.
